### ISSUE TITLE
Needs a name change, cant start with Arduino

### ISSUE THREAD

**Issue by hpssjellis** [iot2tangle/Arduino-I2T-lib#1]
As per

[https://arduino.github.io/arduino-cli/latest/library-specification/ ](https://arduino.github.io/arduino-cli/latest/library-specification/)

"They must contain at least one letter. Note that libraries with a name value starting with Arduino will no longer be allowed"

What can we call it that gets across that it is for Arduinos.

Suggest iota-arduino-I2T-lib

**Comment by Gustbel** [comment]
Thanks for the input. 

Library name changed to: 'I2T-iota-arduino-lib'
